### ISSUE TITLE
Scala Native support

### ISSUE THREAD

**Issue by david-bouyssie** [plokhotnyuk/fast-string-interpolator#213]
Hi.

I'm wondering what would be a blocker for Scala Native support.

Thank you for this nice library and for your input.

**Comment by david-bouyssie** [comment]
Rocket man 🚀 

This is amazing.

**Comment by plokhotnyuk** [comment]
@david-bouyssie Thanks! Just cut a release for it: https://github.com/plokhotnyuk/fast-string-interpolator/releases/tag/v0.6.3
